title:
  patterns:
    - '(Docs|Breaking|Improvement|Fix|Refactor|Feat|Security):\s[A-Z]*-\d+.*'
    - 'Build:\d+\.\d+\.\d'
  error: >-
    You have to include [<change-type>:<ticket number>] or Build:X.X.X> into
    your title
body:
  patterns:
    - "[\\s\\S]*\\[x\\] I have implemented all requirements[\\s\\S]*\\[x\\] I am not affecting someone else's work[\\s\\S]*"
  error: Found unchecked checkbox, all checkboxes must be checked
version: 1
