"""
Copyright 2023 Impulse Innovations Limited


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

# generated by datamodel-codegen:
#   filename:  css-schema.json
#   timestamp: 2022-07-07T11:51:57+00:00

from __future__ import annotations

from enum import Enum


class AlignmentBaseline(Enum):
    _moz_initial = '-moz-initial'
    after_edge = 'after-edge'
    alphabetic = 'alphabetic'
    auto = 'auto'
    baseline = 'baseline'
    before_edge = 'before-edge'
    central = 'central'
    hanging = 'hanging'
    ideographic = 'ideographic'
    inherit = 'inherit'
    initial = 'initial'
    mathematical = 'mathematical'
    middle = 'middle'
    revert = 'revert'
    text_after_edge = 'text-after-edge'
    text_before_edge = 'text-before-edge'
    unset = 'unset'


class All(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    unset = 'unset'


class Appearance(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    button = 'button'
    checkbox = 'checkbox'
    inherit = 'inherit'
    initial = 'initial'
    listbox = 'listbox'
    menulist = 'menulist'
    menulist_button = 'menulist-button'
    meter = 'meter'
    none = 'none'
    progress_bar = 'progress-bar'
    push_button = 'push-button'
    radio = 'radio'
    revert = 'revert'
    searchfield = 'searchfield'
    slider_horizontal = 'slider-horizontal'
    square_button = 'square-button'
    textarea = 'textarea'
    textfield = 'textfield'
    unset = 'unset'


class BackfaceVisibility(Enum):
    _moz_initial = '-moz-initial'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    unset = 'unset'
    visible = 'visible'


class BorderBlockEndStyle(Enum):
    _moz_initial = '-moz-initial'
    dashed = 'dashed'
    dotted = 'dotted'
    double = 'double'
    groove = 'groove'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    inset = 'inset'
    none = 'none'
    outset = 'outset'
    revert = 'revert'
    ridge = 'ridge'
    solid = 'solid'
    unset = 'unset'


class BorderBlockStartStyle(Enum):
    _moz_initial = '-moz-initial'
    dashed = 'dashed'
    dotted = 'dotted'
    double = 'double'
    groove = 'groove'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    inset = 'inset'
    none = 'none'
    outset = 'outset'
    revert = 'revert'
    ridge = 'ridge'
    solid = 'solid'
    unset = 'unset'


class BorderBlockStyle(Enum):
    _moz_initial = '-moz-initial'
    dashed = 'dashed'
    dotted = 'dotted'
    double = 'double'
    groove = 'groove'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    inset = 'inset'
    none = 'none'
    outset = 'outset'
    revert = 'revert'
    ridge = 'ridge'
    solid = 'solid'
    unset = 'unset'


class BorderBottomStyle(Enum):
    _moz_initial = '-moz-initial'
    dashed = 'dashed'
    dotted = 'dotted'
    double = 'double'
    groove = 'groove'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    inset = 'inset'
    none = 'none'
    outset = 'outset'
    revert = 'revert'
    ridge = 'ridge'
    solid = 'solid'
    unset = 'unset'


class BorderCollapse(Enum):
    _moz_initial = '-moz-initial'
    collapse = 'collapse'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    separate = 'separate'
    unset = 'unset'


class BorderInlineEndStyle(Enum):
    _moz_initial = '-moz-initial'
    dashed = 'dashed'
    dotted = 'dotted'
    double = 'double'
    groove = 'groove'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    inset = 'inset'
    none = 'none'
    outset = 'outset'
    revert = 'revert'
    ridge = 'ridge'
    solid = 'solid'
    unset = 'unset'


class BorderInlineStartStyle(Enum):
    _moz_initial = '-moz-initial'
    dashed = 'dashed'
    dotted = 'dotted'
    double = 'double'
    groove = 'groove'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    inset = 'inset'
    none = 'none'
    outset = 'outset'
    revert = 'revert'
    ridge = 'ridge'
    solid = 'solid'
    unset = 'unset'


class BorderInlineStyle(Enum):
    _moz_initial = '-moz-initial'
    dashed = 'dashed'
    dotted = 'dotted'
    double = 'double'
    groove = 'groove'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    inset = 'inset'
    none = 'none'
    outset = 'outset'
    revert = 'revert'
    ridge = 'ridge'
    solid = 'solid'
    unset = 'unset'


class BorderLeftStyle(Enum):
    _moz_initial = '-moz-initial'
    dashed = 'dashed'
    dotted = 'dotted'
    double = 'double'
    groove = 'groove'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    inset = 'inset'
    none = 'none'
    outset = 'outset'
    revert = 'revert'
    ridge = 'ridge'
    solid = 'solid'
    unset = 'unset'


class BorderRightStyle(Enum):
    _moz_initial = '-moz-initial'
    dashed = 'dashed'
    dotted = 'dotted'
    double = 'double'
    groove = 'groove'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    inset = 'inset'
    none = 'none'
    outset = 'outset'
    revert = 'revert'
    ridge = 'ridge'
    solid = 'solid'
    unset = 'unset'


class BorderTopStyle(Enum):
    _moz_initial = '-moz-initial'
    dashed = 'dashed'
    dotted = 'dotted'
    double = 'double'
    groove = 'groove'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    inset = 'inset'
    none = 'none'
    outset = 'outset'
    revert = 'revert'
    ridge = 'ridge'
    solid = 'solid'
    unset = 'unset'


class BoxAlign(Enum):
    _moz_initial = '-moz-initial'
    baseline = 'baseline'
    center = 'center'
    end = 'end'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    start = 'start'
    stretch = 'stretch'
    unset = 'unset'


class BoxDecorationBreak(Enum):
    _moz_initial = '-moz-initial'
    clone = 'clone'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    slice = 'slice'
    unset = 'unset'


class BoxDirection(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    normal = 'normal'
    reverse = 'reverse'
    revert = 'revert'
    unset = 'unset'


class BoxLines(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    multiple = 'multiple'
    revert = 'revert'
    single = 'single'
    unset = 'unset'


class BoxOrient(Enum):
    _moz_initial = '-moz-initial'
    block_axis = 'block-axis'
    horizontal = 'horizontal'
    inherit = 'inherit'
    initial = 'initial'
    inline_axis = 'inline-axis'
    revert = 'revert'
    unset = 'unset'
    vertical = 'vertical'


class BoxPack(Enum):
    _moz_initial = '-moz-initial'
    center = 'center'
    end = 'end'
    inherit = 'inherit'
    initial = 'initial'
    justify = 'justify'
    revert = 'revert'
    start = 'start'
    unset = 'unset'


class BoxSizing(Enum):
    _moz_initial = '-moz-initial'
    border_box = 'border-box'
    content_box = 'content-box'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    unset = 'unset'


class BreakAfter(Enum):
    _moz_initial = '-moz-initial'
    all = 'all'
    always = 'always'
    auto = 'auto'
    avoid = 'avoid'
    avoid_column = 'avoid-column'
    avoid_page = 'avoid-page'
    avoid_region = 'avoid-region'
    column = 'column'
    inherit = 'inherit'
    initial = 'initial'
    left = 'left'
    page = 'page'
    recto = 'recto'
    region = 'region'
    revert = 'revert'
    right = 'right'
    unset = 'unset'
    verso = 'verso'


class BreakBefore(Enum):
    _moz_initial = '-moz-initial'
    all = 'all'
    always = 'always'
    auto = 'auto'
    avoid = 'avoid'
    avoid_column = 'avoid-column'
    avoid_page = 'avoid-page'
    avoid_region = 'avoid-region'
    column = 'column'
    inherit = 'inherit'
    initial = 'initial'
    left = 'left'
    page = 'page'
    recto = 'recto'
    region = 'region'
    revert = 'revert'
    right = 'right'
    unset = 'unset'
    verso = 'verso'


class BreakInside(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    avoid = 'avoid'
    avoid_column = 'avoid-column'
    avoid_page = 'avoid-page'
    avoid_region = 'avoid-region'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    unset = 'unset'


class CaptionSide(Enum):
    _moz_initial = '-moz-initial'
    block_end = 'block-end'
    block_start = 'block-start'
    bottom = 'bottom'
    inherit = 'inherit'
    initial = 'initial'
    inline_end = 'inline-end'
    inline_start = 'inline-start'
    revert = 'revert'
    top = 'top'
    unset = 'unset'


class Clear(Enum):
    _moz_initial = '-moz-initial'
    both = 'both'
    inherit = 'inherit'
    initial = 'initial'
    inline_end = 'inline-end'
    inline_start = 'inline-start'
    left = 'left'
    none = 'none'
    revert = 'revert'
    right = 'right'
    unset = 'unset'


class ClipRule(Enum):
    _moz_initial = '-moz-initial'
    evenodd = 'evenodd'
    inherit = 'inherit'
    initial = 'initial'
    nonzero = 'nonzero'
    revert = 'revert'
    unset = 'unset'


class ColorAdjust(Enum):
    _moz_initial = '-moz-initial'
    economy = 'economy'
    exact = 'exact'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    unset = 'unset'


class ColorInterpolation(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    linearRGB = 'linearRGB'
    revert = 'revert'
    sRGB = 'sRGB'
    unset = 'unset'


class ColorRendering(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    optimizeQuality = 'optimizeQuality'
    optimizeSpeed = 'optimizeSpeed'
    revert = 'revert'
    unset = 'unset'


class ColumnFill(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    balance = 'balance'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    unset = 'unset'


class ColumnSpan(Enum):
    _moz_initial = '-moz-initial'
    all = 'all'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class ContentVisibility(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    unset = 'unset'
    visible = 'visible'


class Direction(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    ltr = 'ltr'
    revert = 'revert'
    rtl = 'rtl'
    unset = 'unset'


class DominantBaseline(Enum):
    _moz_initial = '-moz-initial'
    alphabetic = 'alphabetic'
    auto = 'auto'
    central = 'central'
    hanging = 'hanging'
    ideographic = 'ideographic'
    inherit = 'inherit'
    initial = 'initial'
    mathematical = 'mathematical'
    middle = 'middle'
    no_change = 'no-change'
    reset_size = 'reset-size'
    revert = 'revert'
    text_after_edge = 'text-after-edge'
    text_before_edge = 'text-before-edge'
    unset = 'unset'
    use_script = 'use-script'


class EmptyCells(Enum):
    _moz_initial = '-moz-initial'
    hide = 'hide'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    show = 'show'
    unset = 'unset'


class FillRule(Enum):
    _moz_initial = '-moz-initial'
    evenodd = 'evenodd'
    inherit = 'inherit'
    initial = 'initial'
    nonzero = 'nonzero'
    revert = 'revert'
    unset = 'unset'


class FlexDirection(Enum):
    _moz_initial = '-moz-initial'
    column = 'column'
    column_reverse = 'column-reverse'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    row = 'row'
    row_reverse = 'row-reverse'
    unset = 'unset'


class FlexWrap(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    nowrap = 'nowrap'
    revert = 'revert'
    unset = 'unset'
    wrap = 'wrap'
    wrap_reverse = 'wrap-reverse'


class Float(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    inline_end = 'inline-end'
    inline_start = 'inline-start'
    left = 'left'
    none = 'none'
    revert = 'revert'
    right = 'right'
    unset = 'unset'


class FontKerning(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    normal = 'normal'
    revert = 'revert'
    unset = 'unset'


class FontOpticalSizing(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class FontVariantCaps(Enum):
    _moz_initial = '-moz-initial'
    all_petite_caps = 'all-petite-caps'
    all_small_caps = 'all-small-caps'
    inherit = 'inherit'
    initial = 'initial'
    normal = 'normal'
    petite_caps = 'petite-caps'
    revert = 'revert'
    small_caps = 'small-caps'
    titling_caps = 'titling-caps'
    unicase = 'unicase'
    unset = 'unset'


class FontVariantPosition(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    normal = 'normal'
    revert = 'revert'
    sub = 'sub'
    super = 'super'
    unset = 'unset'


class ForcedColorAdjust(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class Hyphens(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    manual = 'manual'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class ImageRendering(Enum):
    _moz_crisp_edges = '-moz-crisp-edges'
    _moz_initial = '-moz-initial'
    _webkit_optimize_contrast = '-webkit-optimize-contrast'
    auto = 'auto'
    crisp_edges = 'crisp-edges'
    inherit = 'inherit'
    initial = 'initial'
    pixelated = 'pixelated'
    revert = 'revert'
    unset = 'unset'


class ImeMode(Enum):
    _moz_initial = '-moz-initial'
    active = 'active'
    auto = 'auto'
    disabled = 'disabled'
    inactive = 'inactive'
    inherit = 'inherit'
    initial = 'initial'
    normal = 'normal'
    revert = 'revert'
    unset = 'unset'


class Isolation(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    isolate = 'isolate'
    revert = 'revert'
    unset = 'unset'


class LineBreak(Enum):
    _moz_initial = '-moz-initial'
    anywhere = 'anywhere'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    loose = 'loose'
    normal = 'normal'
    revert = 'revert'
    strict = 'strict'
    unset = 'unset'


class ListStylePosition(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    inside = 'inside'
    outside = 'outside'
    revert = 'revert'
    unset = 'unset'


class MaskBorderMode(Enum):
    _moz_initial = '-moz-initial'
    alpha = 'alpha'
    inherit = 'inherit'
    initial = 'initial'
    luminance = 'luminance'
    revert = 'revert'
    unset = 'unset'


class MaskType(Enum):
    _moz_initial = '-moz-initial'
    alpha = 'alpha'
    inherit = 'inherit'
    initial = 'initial'
    luminance = 'luminance'
    revert = 'revert'
    unset = 'unset'


class MathStyle(Enum):
    _moz_initial = '-moz-initial'
    compact = 'compact'
    inherit = 'inherit'
    initial = 'initial'
    normal = 'normal'
    revert = 'revert'
    unset = 'unset'


class MixBlendMode(Enum):
    _moz_initial = '-moz-initial'
    color = 'color'
    color_burn = 'color-burn'
    color_dodge = 'color-dodge'
    darken = 'darken'
    difference = 'difference'
    exclusion = 'exclusion'
    hard_light = 'hard-light'
    hue = 'hue'
    inherit = 'inherit'
    initial = 'initial'
    lighten = 'lighten'
    luminosity = 'luminosity'
    multiply = 'multiply'
    normal = 'normal'
    overlay = 'overlay'
    revert = 'revert'
    saturation = 'saturation'
    screen = 'screen'
    soft_light = 'soft-light'
    unset = 'unset'


class MozAppearance(Enum):
    _moz_initial = '-moz-initial'
    _moz_mac_unified_toolbar = '-moz-mac-unified-toolbar'
    _moz_win_borderless_glass = '-moz-win-borderless-glass'
    _moz_win_browsertabbar_toolbox = '-moz-win-browsertabbar-toolbox'
    _moz_win_communications_toolbox = '-moz-win-communications-toolbox'
    _moz_win_communicationstext = '-moz-win-communicationstext'
    _moz_win_exclude_glass = '-moz-win-exclude-glass'
    _moz_win_glass = '-moz-win-glass'
    _moz_win_media_toolbox = '-moz-win-media-toolbox'
    _moz_win_mediatext = '-moz-win-mediatext'
    _moz_window_button_box = '-moz-window-button-box'
    _moz_window_button_box_maximized = '-moz-window-button-box-maximized'
    _moz_window_button_close = '-moz-window-button-close'
    _moz_window_button_maximize = '-moz-window-button-maximize'
    _moz_window_button_minimize = '-moz-window-button-minimize'
    _moz_window_button_restore = '-moz-window-button-restore'
    _moz_window_frame_bottom = '-moz-window-frame-bottom'
    _moz_window_frame_left = '-moz-window-frame-left'
    _moz_window_frame_right = '-moz-window-frame-right'
    _moz_window_titlebar = '-moz-window-titlebar'
    _moz_window_titlebar_maximized = '-moz-window-titlebar-maximized'
    button = 'button'
    button_arrow_down = 'button-arrow-down'
    button_arrow_next = 'button-arrow-next'
    button_arrow_previous = 'button-arrow-previous'
    button_arrow_up = 'button-arrow-up'
    button_bevel = 'button-bevel'
    button_focus = 'button-focus'
    caret = 'caret'
    checkbox = 'checkbox'
    checkbox_container = 'checkbox-container'
    checkbox_label = 'checkbox-label'
    checkmenuitem = 'checkmenuitem'
    dualbutton = 'dualbutton'
    groupbox = 'groupbox'
    inherit = 'inherit'
    initial = 'initial'
    listbox = 'listbox'
    listitem = 'listitem'
    menuarrow = 'menuarrow'
    menubar = 'menubar'
    menucheckbox = 'menucheckbox'
    menuimage = 'menuimage'
    menuitem = 'menuitem'
    menuitemtext = 'menuitemtext'
    menulist = 'menulist'
    menulist_button = 'menulist-button'
    menulist_text = 'menulist-text'
    menulist_textfield = 'menulist-textfield'
    menupopup = 'menupopup'
    menuradio = 'menuradio'
    menuseparator = 'menuseparator'
    meterbar = 'meterbar'
    meterchunk = 'meterchunk'
    none = 'none'
    progressbar = 'progressbar'
    progressbar_vertical = 'progressbar-vertical'
    progresschunk = 'progresschunk'
    progresschunk_vertical = 'progresschunk-vertical'
    radio = 'radio'
    radio_container = 'radio-container'
    radio_label = 'radio-label'
    radiomenuitem = 'radiomenuitem'
    range = 'range'
    range_thumb = 'range-thumb'
    resizer = 'resizer'
    resizerpanel = 'resizerpanel'
    revert = 'revert'
    scale_horizontal = 'scale-horizontal'
    scale_vertical = 'scale-vertical'
    scalethumb_horizontal = 'scalethumb-horizontal'
    scalethumb_vertical = 'scalethumb-vertical'
    scalethumbend = 'scalethumbend'
    scalethumbstart = 'scalethumbstart'
    scalethumbtick = 'scalethumbtick'
    scrollbarbutton_down = 'scrollbarbutton-down'
    scrollbarbutton_left = 'scrollbarbutton-left'
    scrollbarbutton_right = 'scrollbarbutton-right'
    scrollbarbutton_up = 'scrollbarbutton-up'
    scrollbarthumb_horizontal = 'scrollbarthumb-horizontal'
    scrollbarthumb_vertical = 'scrollbarthumb-vertical'
    scrollbartrack_horizontal = 'scrollbartrack-horizontal'
    scrollbartrack_vertical = 'scrollbartrack-vertical'
    searchfield = 'searchfield'
    separator = 'separator'
    sheet = 'sheet'
    spinner = 'spinner'
    spinner_downbutton = 'spinner-downbutton'
    spinner_textfield = 'spinner-textfield'
    spinner_upbutton = 'spinner-upbutton'
    splitter = 'splitter'
    statusbar = 'statusbar'
    statusbarpanel = 'statusbarpanel'
    tab = 'tab'
    tab_scroll_arrow_back = 'tab-scroll-arrow-back'
    tab_scroll_arrow_forward = 'tab-scroll-arrow-forward'
    tabpanel = 'tabpanel'
    tabpanels = 'tabpanels'
    textfield = 'textfield'
    textfield_multiline = 'textfield-multiline'
    toolbar = 'toolbar'
    toolbarbutton = 'toolbarbutton'
    toolbarbutton_dropdown = 'toolbarbutton-dropdown'
    toolbargripper = 'toolbargripper'
    toolbox = 'toolbox'
    tooltip = 'tooltip'
    treeheader = 'treeheader'
    treeheadercell = 'treeheadercell'
    treeheadersortarrow = 'treeheadersortarrow'
    treeitem = 'treeitem'
    treeline = 'treeline'
    treetwisty = 'treetwisty'
    treetwistyopen = 'treetwistyopen'
    treeview = 'treeview'
    unset = 'unset'


class MozFloatEdge(Enum):
    _moz_initial = '-moz-initial'
    border_box = 'border-box'
    content_box = 'content-box'
    inherit = 'inherit'
    initial = 'initial'
    margin_box = 'margin-box'
    padding_box = 'padding-box'
    revert = 'revert'
    unset = 'unset'


class MozOrient(Enum):
    _moz_initial = '-moz-initial'
    block = 'block'
    horizontal = 'horizontal'
    inherit = 'inherit'
    initial = 'initial'
    inline = 'inline'
    revert = 'revert'
    unset = 'unset'
    vertical = 'vertical'


class MozStackSizing(Enum):
    _moz_initial = '-moz-initial'
    ignore = 'ignore'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    stretch_to_fit = 'stretch-to-fit'
    unset = 'unset'


class MozTextBlink(Enum):
    _moz_initial = '-moz-initial'
    blink = 'blink'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class MozUserFocus(Enum):
    _moz_initial = '-moz-initial'
    ignore = 'ignore'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    normal = 'normal'
    revert = 'revert'
    select_after = 'select-after'
    select_all = 'select-all'
    select_before = 'select-before'
    select_menu = 'select-menu'
    select_same = 'select-same'
    unset = 'unset'


class MozUserInput(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    disabled = 'disabled'
    enabled = 'enabled'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class MozUserModify(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    read_only = 'read-only'
    read_write = 'read-write'
    revert = 'revert'
    unset = 'unset'
    write_only = 'write-only'


class MozWindowDragging(Enum):
    _moz_initial = '-moz-initial'
    drag = 'drag'
    inherit = 'inherit'
    initial = 'initial'
    no_drag = 'no-drag'
    revert = 'revert'
    unset = 'unset'


class MozWindowShadow(Enum):
    _moz_initial = '-moz-initial'
    default = 'default'
    inherit = 'inherit'
    initial = 'initial'
    menu = 'menu'
    none = 'none'
    revert = 'revert'
    sheet = 'sheet'
    tooltip = 'tooltip'
    unset = 'unset'


class MsAccelerator(Enum):
    _moz_initial = '-moz-initial'
    false = 'false'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    true = 'true'
    unset = 'unset'


class MsBlockProgression(Enum):
    _moz_initial = '-moz-initial'
    bt = 'bt'
    inherit = 'inherit'
    initial = 'initial'
    lr = 'lr'
    revert = 'revert'
    rl = 'rl'
    tb = 'tb'
    unset = 'unset'


class MsContentZoomChaining(Enum):
    _moz_initial = '-moz-initial'
    chained = 'chained'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class MsContentZoomSnapType(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    mandatory = 'mandatory'
    none = 'none'
    proximity = 'proximity'
    revert = 'revert'
    unset = 'unset'


class MsContentZooming(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'
    zoom = 'zoom'


class MsHighContrastAdjust(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class MsImeAlign(Enum):
    _moz_initial = '-moz-initial'
    after = 'after'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    unset = 'unset'


class MsOverflowStyle(Enum):
    _moz_initial = '-moz-initial'
    _ms_autohiding_scrollbar = '-ms-autohiding-scrollbar'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    scrollbar = 'scrollbar'
    unset = 'unset'


class MsScrollChaining(Enum):
    _moz_initial = '-moz-initial'
    chained = 'chained'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class MsScrollRails(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    railed = 'railed'
    revert = 'revert'
    unset = 'unset'


class MsScrollSnapType(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    mandatory = 'mandatory'
    none = 'none'
    proximity = 'proximity'
    revert = 'revert'
    unset = 'unset'


class MsScrollTranslation(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'
    vertical_to_horizontal = 'vertical-to-horizontal'


class MsTextAutospace(Enum):
    _moz_initial = '-moz-initial'
    ideograph_alpha = 'ideograph-alpha'
    ideograph_numeric = 'ideograph-numeric'
    ideograph_parenthesis = 'ideograph-parenthesis'
    ideograph_space = 'ideograph-space'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class MsTouchSelect(Enum):
    _moz_initial = '-moz-initial'
    grippers = 'grippers'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class MsUserSelect(Enum):
    _moz_initial = '-moz-initial'
    element = 'element'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    text = 'text'
    unset = 'unset'


class MsWrapFlow(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    both = 'both'
    clear = 'clear'
    end = 'end'
    inherit = 'inherit'
    initial = 'initial'
    maximum = 'maximum'
    revert = 'revert'
    start = 'start'
    unset = 'unset'


class MsWrapThrough(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'
    wrap = 'wrap'


class ObjectFit(Enum):
    _moz_initial = '-moz-initial'
    contain = 'contain'
    cover = 'cover'
    fill = 'fill'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    scale_down = 'scale-down'
    unset = 'unset'


class OverflowAnchor(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class OverflowBlock(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    clip = 'clip'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    scroll = 'scroll'
    unset = 'unset'
    visible = 'visible'


class OverflowClipBox(Enum):
    _moz_initial = '-moz-initial'
    content_box = 'content-box'
    inherit = 'inherit'
    initial = 'initial'
    padding_box = 'padding-box'
    revert = 'revert'
    unset = 'unset'


class OverflowInline(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    clip = 'clip'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    scroll = 'scroll'
    unset = 'unset'
    visible = 'visible'


class OverflowWrap(Enum):
    _moz_initial = '-moz-initial'
    anywhere = 'anywhere'
    break_word = 'break-word'
    inherit = 'inherit'
    initial = 'initial'
    normal = 'normal'
    revert = 'revert'
    unset = 'unset'


class OverflowX(Enum):
    _moz_hidden_unscrollable = '-moz-hidden-unscrollable'
    _moz_initial = '-moz-initial'
    auto = 'auto'
    clip = 'clip'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    scroll = 'scroll'
    unset = 'unset'
    visible = 'visible'


class OverflowY(Enum):
    _moz_hidden_unscrollable = '-moz-hidden-unscrollable'
    _moz_initial = '-moz-initial'
    auto = 'auto'
    clip = 'clip'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    scroll = 'scroll'
    unset = 'unset'
    visible = 'visible'


class OverscrollBehaviorBlock(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    contain = 'contain'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class OverscrollBehaviorInline(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    contain = 'contain'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class OverscrollBehaviorX(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    contain = 'contain'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class OverscrollBehaviorY(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    contain = 'contain'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class PageBreakAfter(Enum):
    _moz_initial = '-moz-initial'
    always = 'always'
    auto = 'auto'
    avoid = 'avoid'
    inherit = 'inherit'
    initial = 'initial'
    left = 'left'
    recto = 'recto'
    revert = 'revert'
    right = 'right'
    unset = 'unset'
    verso = 'verso'


class PageBreakBefore(Enum):
    _moz_initial = '-moz-initial'
    always = 'always'
    auto = 'auto'
    avoid = 'avoid'
    inherit = 'inherit'
    initial = 'initial'
    left = 'left'
    recto = 'recto'
    revert = 'revert'
    right = 'right'
    unset = 'unset'
    verso = 'verso'


class PageBreakInside(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    avoid = 'avoid'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    unset = 'unset'


class PointerEvents(Enum):
    _moz_initial = '-moz-initial'
    all = 'all'
    auto = 'auto'
    fill = 'fill'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    painted = 'painted'
    revert = 'revert'
    stroke = 'stroke'
    unset = 'unset'
    visible = 'visible'
    visibleFill = 'visibleFill'
    visiblePainted = 'visiblePainted'
    visibleStroke = 'visibleStroke'


class Position(Enum):
    _moz_initial = '-moz-initial'
    _webkit_sticky = '-webkit-sticky'
    absolute = 'absolute'
    fixed = 'fixed'
    inherit = 'inherit'
    initial = 'initial'
    relative = 'relative'
    revert = 'revert'
    static = 'static'
    sticky = 'sticky'
    unset = 'unset'


class Resize(Enum):
    _moz_initial = '-moz-initial'
    block = 'block'
    both = 'both'
    horizontal = 'horizontal'
    inherit = 'inherit'
    initial = 'initial'
    inline = 'inline'
    none = 'none'
    revert = 'revert'
    unset = 'unset'
    vertical = 'vertical'


class RubyAlign(Enum):
    _moz_initial = '-moz-initial'
    center = 'center'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    space_around = 'space-around'
    space_between = 'space-between'
    start = 'start'
    unset = 'unset'


class RubyMerge(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    collapse = 'collapse'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    separate = 'separate'
    unset = 'unset'


class ScrollBehavior(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    smooth = 'smooth'
    unset = 'unset'


class ScrollSnapStop(Enum):
    _moz_initial = '-moz-initial'
    always = 'always'
    inherit = 'inherit'
    initial = 'initial'
    normal = 'normal'
    revert = 'revert'
    unset = 'unset'


class ScrollSnapTypeX(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    mandatory = 'mandatory'
    none = 'none'
    proximity = 'proximity'
    revert = 'revert'
    unset = 'unset'


class ScrollSnapTypeY(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    mandatory = 'mandatory'
    none = 'none'
    proximity = 'proximity'
    revert = 'revert'
    unset = 'unset'


class ScrollbarWidth(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    thin = 'thin'
    unset = 'unset'


class ShapeRendering(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    crispEdges = 'crispEdges'
    geometricPrecision = 'geometricPrecision'
    inherit = 'inherit'
    initial = 'initial'
    optimizeSpeed = 'optimizeSpeed'
    revert = 'revert'
    unset = 'unset'


class StrokeLinecap(Enum):
    _moz_initial = '-moz-initial'
    butt = 'butt'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    round = 'round'
    square = 'square'
    unset = 'unset'


class StrokeLinejoin(Enum):
    _moz_initial = '-moz-initial'
    bevel = 'bevel'
    inherit = 'inherit'
    initial = 'initial'
    miter = 'miter'
    revert = 'revert'
    round = 'round'
    unset = 'unset'


class TableLayout(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    fixed = 'fixed'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    unset = 'unset'


class TextAlign(Enum):
    _moz_initial = '-moz-initial'
    center = 'center'
    end = 'end'
    inherit = 'inherit'
    initial = 'initial'
    justify = 'justify'
    left = 'left'
    match_parent = 'match-parent'
    revert = 'revert'
    right = 'right'
    start = 'start'
    unset = 'unset'


class TextAlignLast(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    center = 'center'
    end = 'end'
    inherit = 'inherit'
    initial = 'initial'
    justify = 'justify'
    left = 'left'
    revert = 'revert'
    right = 'right'
    start = 'start'
    unset = 'unset'


class TextAnchor(Enum):
    _moz_initial = '-moz-initial'
    end = 'end'
    inherit = 'inherit'
    initial = 'initial'
    middle = 'middle'
    revert = 'revert'
    start = 'start'
    unset = 'unset'


class TextDecorationSkipInk(Enum):
    _moz_initial = '-moz-initial'
    all = 'all'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class TextDecorationStyle(Enum):
    _moz_initial = '-moz-initial'
    dashed = 'dashed'
    dotted = 'dotted'
    double = 'double'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    solid = 'solid'
    unset = 'unset'
    wavy = 'wavy'


class TextJustify(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    inter_character = 'inter-character'
    inter_word = 'inter-word'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class TextOrientation(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    mixed = 'mixed'
    revert = 'revert'
    sideways = 'sideways'
    unset = 'unset'
    upright = 'upright'


class TextRendering(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    geometricPrecision = 'geometricPrecision'
    inherit = 'inherit'
    initial = 'initial'
    optimizeLegibility = 'optimizeLegibility'
    optimizeSpeed = 'optimizeSpeed'
    revert = 'revert'
    unset = 'unset'


class TextTransform(Enum):
    _moz_initial = '-moz-initial'
    capitalize = 'capitalize'
    full_size_kana = 'full-size-kana'
    full_width = 'full-width'
    inherit = 'inherit'
    initial = 'initial'
    lowercase = 'lowercase'
    none = 'none'
    revert = 'revert'
    unset = 'unset'
    uppercase = 'uppercase'


class TransformBox(Enum):
    _moz_initial = '-moz-initial'
    border_box = 'border-box'
    content_box = 'content-box'
    fill_box = 'fill-box'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    stroke_box = 'stroke-box'
    unset = 'unset'
    view_box = 'view-box'


class TransformStyle(Enum):
    _moz_initial = '-moz-initial'
    flat = 'flat'
    inherit = 'inherit'
    initial = 'initial'
    preserve_3d = 'preserve-3d'
    revert = 'revert'
    unset = 'unset'


class UnicodeBidi(Enum):
    _moz_initial = '-moz-initial'
    _moz_isolate = '-moz-isolate'
    _moz_isolate_override = '-moz-isolate-override'
    _moz_plaintext = '-moz-plaintext'
    _webkit_isolate = '-webkit-isolate'
    _webkit_isolate_override = '-webkit-isolate-override'
    _webkit_plaintext = '-webkit-plaintext'
    bidi_override = 'bidi-override'
    embed = 'embed'
    inherit = 'inherit'
    initial = 'initial'
    isolate = 'isolate'
    isolate_override = 'isolate-override'
    normal = 'normal'
    plaintext = 'plaintext'
    revert = 'revert'
    unset = 'unset'


class UserSelect(Enum):
    _moz_initial = '-moz-initial'
    _moz_none = '-moz-none'
    all = 'all'
    auto = 'auto'
    contain = 'contain'
    element = 'element'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    text = 'text'
    unset = 'unset'


class VectorEffect(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    non_scaling_stroke = 'non-scaling-stroke'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class Visibility(Enum):
    _moz_initial = '-moz-initial'
    collapse = 'collapse'
    hidden = 'hidden'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    unset = 'unset'
    visible = 'visible'


class WebkitAppearance(Enum):
    _apple_pay_button = '-apple-pay-button'
    _moz_initial = '-moz-initial'
    button = 'button'
    button_bevel = 'button-bevel'
    caret = 'caret'
    checkbox = 'checkbox'
    default_button = 'default-button'
    inherit = 'inherit'
    initial = 'initial'
    inner_spin_button = 'inner-spin-button'
    listbox = 'listbox'
    listitem = 'listitem'
    media_controls_background = 'media-controls-background'
    media_controls_fullscreen_background = 'media-controls-fullscreen-background'
    media_current_time_display = 'media-current-time-display'
    media_enter_fullscreen_button = 'media-enter-fullscreen-button'
    media_exit_fullscreen_button = 'media-exit-fullscreen-button'
    media_fullscreen_button = 'media-fullscreen-button'
    media_mute_button = 'media-mute-button'
    media_overlay_play_button = 'media-overlay-play-button'
    media_play_button = 'media-play-button'
    media_seek_back_button = 'media-seek-back-button'
    media_seek_forward_button = 'media-seek-forward-button'
    media_slider = 'media-slider'
    media_sliderthumb = 'media-sliderthumb'
    media_time_remaining_display = 'media-time-remaining-display'
    media_toggle_closed_captions_button = 'media-toggle-closed-captions-button'
    media_volume_slider = 'media-volume-slider'
    media_volume_slider_container = 'media-volume-slider-container'
    media_volume_sliderthumb = 'media-volume-sliderthumb'
    menulist = 'menulist'
    menulist_button = 'menulist-button'
    menulist_text = 'menulist-text'
    menulist_textfield = 'menulist-textfield'
    meter = 'meter'
    none = 'none'
    progress_bar = 'progress-bar'
    progress_bar_value = 'progress-bar-value'
    push_button = 'push-button'
    radio = 'radio'
    revert = 'revert'
    searchfield = 'searchfield'
    searchfield_cancel_button = 'searchfield-cancel-button'
    searchfield_decoration = 'searchfield-decoration'
    searchfield_results_button = 'searchfield-results-button'
    searchfield_results_decoration = 'searchfield-results-decoration'
    slider_horizontal = 'slider-horizontal'
    slider_vertical = 'slider-vertical'
    sliderthumb_horizontal = 'sliderthumb-horizontal'
    sliderthumb_vertical = 'sliderthumb-vertical'
    square_button = 'square-button'
    textarea = 'textarea'
    textfield = 'textfield'
    unset = 'unset'


class WebkitMaskRepeatX(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    no_repeat = 'no-repeat'
    repeat = 'repeat'
    revert = 'revert'
    round = 'round'
    space = 'space'
    unset = 'unset'


class WebkitMaskRepeatY(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    no_repeat = 'no-repeat'
    repeat = 'repeat'
    revert = 'revert'
    round = 'round'
    space = 'space'
    unset = 'unset'


class WebkitOverflowScrolling(Enum):
    _moz_initial = '-moz-initial'
    auto = 'auto'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    touch = 'touch'
    unset = 'unset'


class WebkitTouchCallout(Enum):
    _moz_initial = '-moz-initial'
    default = 'default'
    inherit = 'inherit'
    initial = 'initial'
    none = 'none'
    revert = 'revert'
    unset = 'unset'


class WebkitUserModify(Enum):
    _moz_initial = '-moz-initial'
    inherit = 'inherit'
    initial = 'initial'
    read_only = 'read-only'
    read_write = 'read-write'
    read_write_plaintext_only = 'read-write-plaintext-only'
    revert = 'revert'
    unset = 'unset'


class WhiteSpace(Enum):
    _moz_initial = '-moz-initial'
    _moz_pre_wrap = '-moz-pre-wrap'
    break_spaces = 'break-spaces'
    inherit = 'inherit'
    initial = 'initial'
    normal = 'normal'
    nowrap = 'nowrap'
    pre = 'pre'
    pre_line = 'pre-line'
    pre_wrap = 'pre-wrap'
    revert = 'revert'
    unset = 'unset'


class WordBreak(Enum):
    _moz_initial = '-moz-initial'
    break_all = 'break-all'
    break_word = 'break-word'
    inherit = 'inherit'
    initial = 'initial'
    keep_all = 'keep-all'
    normal = 'normal'
    revert = 'revert'
    unset = 'unset'


class WordWrap(Enum):
    _moz_initial = '-moz-initial'
    break_word = 'break-word'
    inherit = 'inherit'
    initial = 'initial'
    normal = 'normal'
    revert = 'revert'
    unset = 'unset'


class WritingMode(Enum):
    _moz_initial = '-moz-initial'
    horizontal_tb = 'horizontal-tb'
    inherit = 'inherit'
    initial = 'initial'
    revert = 'revert'
    sideways_lr = 'sideways-lr'
    sideways_rl = 'sideways-rl'
    unset = 'unset'
    vertical_lr = 'vertical-lr'
    vertical_rl = 'vertical-rl'
