"""Development server configuration and identity handshake."""

import os
from base64 import urlsafe_b64decode, urlsafe_b64encode
from pathlib import Path
from typing import Literal

import httpx
from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings, SettingsConfigDict

DEV_SERVER_INFO_PATH = '/__dara__/dev-server-info'


class DevServerSettings(BaseSettings):
    """Settings shared by the Dara backend and Vite development server."""

    protocol: Literal['http', 'https'] = 'http'
    host: str = 'localhost'
    port: int = Field(default=3000, ge=1, le=65535)

    model_config = SettingsConfigDict(env_file='.env', env_prefix='VITE_SERVER_', extra='ignore')

    @property
    def origin(self) -> str:
        """Return the browser-visible Vite server origin."""
        return f'{self.protocol}://{self.host}:{self.port}'

    def as_environment(self) -> dict[str, str]:
        """Return settings in the format consumed by Vite and fastapi-vite."""
        return {
            'VITE_SERVER_HOST': self.host,
            'VITE_SERVER_PORT': str(self.port),
            'VITE_SERVER_PROTOCOL': self.protocol,
        }


class DevServerInfo(BaseModel):
    """Identify one Dara project and its Vite development server."""

    version: Literal[1] = 1
    cwd: str
    static_files_dir: str
    origin: str

    @classmethod
    def from_static_files_dir(
        cls,
        static_files_dir: str,
        cwd: str | os.PathLike[str] | None = None,
        settings: DevServerSettings | None = None,
    ) -> 'DevServerInfo':
        """Create identity information using canonical paths and resolved development settings."""
        project_cwd = Path(cwd or os.getcwd()).resolve()
        static_path = Path(static_files_dir)

        if not static_path.is_absolute():
            static_path = project_cwd / static_path

        return cls(
            cwd=str(project_cwd),
            static_files_dir=str(static_path.resolve()),
            origin=(settings or DevServerSettings()).origin,
        )

    @classmethod
    def decode(cls, encoded: str) -> 'DevServerInfo':
        """Decode and parse a base64url identity."""
        return cls.model_validate_json(urlsafe_b64decode(encoded).decode('utf-8'))

    def encode(self) -> str:
        """Encode the identity as base64url JSON for transport through an environment variable."""
        return urlsafe_b64encode(self.model_dump_json().encode('utf-8')).decode('ascii')


class DevServerInfoResponse(BaseModel):
    """Response returned by Dara's Vite development server endpoint."""

    info: str


class UnidentifiedDevServerMismatch(BaseModel):
    """Describe an unavailable, malformed, or incompatible development server."""

    reason: Literal['unidentified-server'] = 'unidentified-server'
    expected: DevServerInfo

    def format_message(self) -> str:
        """Format a mismatch for the development-only error page."""
        return f"""No compatible Dara dev server responded at:
{self.expected.origin}

The server is unavailable, is not a Dara dev server, or was generated by an older Dara version.

Run `dara dev` from:
{self.expected.cwd}"""


class WrongDevServerMismatch(BaseModel):
    """Describe a valid development server running for a different Dara project."""

    reason: Literal['wrong-server'] = 'wrong-server'
    expected: DevServerInfo
    actual: DevServerInfo

    def format_message(self) -> str:
        """Format a mismatch for the development-only error page."""
        return f"""This application expects assets from:
{self.expected.static_files_dir}

{self.expected.origin} is currently serving assets from:
{self.actual.static_files_dir}

Stop `dara dev` in:
{self.actual.cwd}

Then run it from:
{self.expected.cwd}"""


DevServerMismatch = UnidentifiedDevServerMismatch | WrongDevServerMismatch


async def check_dev_server(expected: DevServerInfo) -> DevServerMismatch | None:
    """Check the configured Vite server and return a mismatch when it is not suitable for this application."""
    try:
        async with httpx.AsyncClient(timeout=1) as client:
            response = await client.get(f'{expected.origin}{DEV_SERVER_INFO_PATH}')
            response.raise_for_status()
            payload = DevServerInfoResponse.model_validate_json(response.content)
            actual = DevServerInfo.decode(payload.info)
    except (httpx.HTTPError, ValueError):
        return UnidentifiedDevServerMismatch(expected=expected)

    if actual.static_files_dir != expected.static_files_dir:
        return WrongDevServerMismatch(expected=expected, actual=actual)

    return None
