"""Translate proven JavaScript sources into Python-owned migration edits."""

import hashlib
import json
import os
import re
from collections.abc import Iterable
from pathlib import Path

from dara.core.js_tooling.migration_analyzer import (
    Analysis,
    ManualEntry,
    ManualSource,
    PackageSource,
    ReadyEntry,
    analyze_sources,
)
from dara.core.js_tooling.migration_plan import MigrationIssue, MigrationPlan, SourceRequest


def _references(text: str) -> list[tuple[str, int]]:
    """Find literal relative paths conservatively, including CSS URLs and HTML attributes."""
    references = []
    for match in re.finditer(r'([\'"`])((?:\\.|(?!\1)[\s\S])*?)\1', text):
        value = match[2]
        if value.startswith(('./', '../', '\\u', '\\x', '.\\')) or value in ('.', '..'):
            references.append((value, match.start(2)))
    # URL contexts also accept bare relative paths: src="frontend/app.tsx" and
    # url(fonts/body.woff). Do not apply this rule to arbitrary JS strings.
    for match in re.finditer(
        r'(?:\burl\(\s*|\b(?:src|href)\s*=\s*)(?:([\'"])(.*?)\1|([^\s\'"`()<>]+))', text, re.I | re.S
    ):
        group = 2 if match[1] else 3
        value = match[group]
        if value and not re.match(r'(?:[A-Za-z][A-Za-z0-9+.-]*:|[/#?])', value):
            references.append((value, match.start(group)))
    return list(dict.fromkeys(references))


class JavaScriptSources:
    """Keep analysis in Node while preserving source text, setup imports and named-export adapters."""

    def __init__(
        self, plan: MigrationPlan, source_root: Path, destination_root: Path, requests: Iterable[SourceRequest] = ()
    ):
        self.plan = plan
        self.source_root = source_root
        self.destination_root = destination_root
        self.requests = list(requests)
        self.analysis: Analysis | None = None
        self.entry: Path | None = None

    def _load(self) -> Analysis:
        if self.analysis is None:
            self.analysis = analyze_sources(self.plan, self.source_root, self.requests)
            if isinstance(self.analysis.entry, ManualEntry):
                issue = MigrationIssue(Path(self.analysis.entry.file), 1, self.analysis.entry.message)
                if issue not in self.plan.issues:
                    self.plan.issues.append(issue)
        return self.analysis

    def _issue(self, request: SourceRequest, message: str) -> None:
        self.plan.issues.append(MigrationIssue(request.path, request.line, f'{request.class_name}: {message}'))

    def prepare_entry(self) -> None:
        """Keep a non-TSX legacy entry reachable from the new fixed index.tsx."""
        analysis = self._load()
        self.entry = Path(analysis.entry.file) if isinstance(analysis.entry, ReadyEntry) else None
        if self.entry is None or self.entry == self.source_root / 'index.tsx':
            return
        if self.entry.suffix in ('.ts', '.mts', '.cts') and not self._allows_typed_imports():
            self.plan.issues.append(
                MigrationIssue(
                    self.entry,
                    1,
                    'Set compilerOptions.allowImportingTsExtensions to true in tsconfig.json (or extend @darajs/vite-plugin/tsconfig.json) before forwarding this legacy entry from index.tsx.',
                )
            )
            return
        fixed = self.destination_root / 'index.tsx'
        relative = './' + self.entry.relative_to(self.source_root).as_posix()
        wrapper = f'// Generated by dara migrate; preserves setup and styles in the legacy entry.\nimport {json.dumps(relative)};\n'
        existing = self.plan.read(fixed)
        source_fixed = self.source_root / 'index.tsx'
        incoming = self.plan.read(source_fixed) if source_fixed != fixed else existing
        if any(value is not None and value != wrapper for value in (existing, incoming)):
            self.plan.issues.append(
                MigrationIssue(
                    fixed,
                    1,
                    'Keep the existing index.tsx and import the legacy entry/setup explicitly; migration will not overwrite either file.',
                )
            )
            return
        self.plan.write(fixed, wrapper)

    def check_relocation(self, files: Iterable[Path]) -> None:
        """Reject relative references whose destination changes outside the relocated tree."""
        if self.source_root == self.destination_root:
            return
        for file in files:
            text = self.plan.read(file) or ''
            destination = self.destination_root / file.relative_to(self.source_root)
            for reference, offset in _references(text):
                line = text.count('\n', 0, offset) + 1
                if '\\' in reference or '${' in reference:
                    self.plan.issues.append(
                        MigrationIssue(
                            file,
                            line,
                            'Resolve this dynamic/escaped relative reference before moving the source tree to js/.',
                        )
                    )
                    continue
                pathname = re.split(r'[?#]', reference, maxsplit=1)[0]
                before = (file.parent / pathname).resolve()
                after = (destination.parent / pathname).resolve()
                if not before.is_relative_to(self.source_root) and before != after:
                    self.plan.issues.append(
                        MigrationIssue(
                            file,
                            line,
                            f'Rewrite the external relative reference {reference!r} before moving the source tree to js/.',
                        )
                    )

    def check_external_references(self, files: Iterable[Path]) -> None:
        """Reject inbound relative references that would keep pointing at the removed source tree."""
        if self.source_root == self.destination_root:
            return
        for file in files:
            if file.is_relative_to(self.source_root) or file.is_relative_to(self.destination_root):
                continue
            if file.suffix not in {
                '.js',
                '.jsx',
                '.ts',
                '.tsx',
                '.mjs',
                '.mts',
                '.cjs',
                '.cts',
                '.css',
                '.scss',
                '.sass',
                '.less',
                '.html',
                '.svg',
                '.json',
            }:
                continue
            text = self.plan.read(file) or ''
            for reference, offset in _references(text):
                target = (file.parent / re.split(r'[?#]', reference, maxsplit=1)[0]).resolve()
                if target.is_relative_to(self.source_root) or '\\' in reference or '${' in reference:
                    self.plan.issues.append(
                        MigrationIssue(
                            file,
                            text.count('\n', 0, offset) + 1,
                            f'Rewrite the reference {reference!r} to the relocated js/ source before migration.',
                        )
                    )

    def resolve(self, request: SourceRequest) -> str | None:
        """Return a proven default-export specifier, proposing an adapter only when necessary."""
        if request not in self.requests:
            self.requests.append(request)
            self.analysis = None
        analysis = self._load()
        result = analysis.resolutions[self.requests.index(request)]
        if isinstance(result, ManualSource):
            self._issue(request, result.message)
            return None
        if isinstance(result, PackageSource):
            return result.source
        implementation = Path(result.file)
        if not implementation.is_relative_to(self.source_root):
            self._issue(request, 'Resolved implementation is outside the local source tree; set js_source manually.')
            return None
        destination = self.destination_root / implementation.relative_to(self.source_root)
        if result.name == 'default':
            return './' + destination.relative_to(self.plan.root).as_posix()
        if destination.suffix in ('.ts', '.tsx', '.mts', '.cts') and not self._allows_typed_imports():
            self._issue(
                request,
                'Set compilerOptions.allowImportingTsExtensions to true in tsconfig.json (or extend @darajs/vite-plugin/tsconfig.json) before generating an adapter with the exact TypeScript source extension.',
            )
            return None
        key = hashlib.sha256(f'{destination.relative_to(self.plan.root)}:{result.name}'.encode()).hexdigest()[:12]
        adapter = self.destination_root / 'dara-adapters' / f'{key}.ts'
        relative = os.path.relpath(destination, adapter.parent).replace(os.sep, '/')
        content = f'// Generated by dara migrate; preserves the existing named export.\nexport {{ {json.dumps(result.name)} as default }} from {json.dumps(relative)};\n'
        existing = self.plan.read(adapter)
        if existing is not None and existing != content:
            self._issue(
                request, f'Keep customized adapter {adapter.relative_to(self.plan.root)} and set js_source manually.'
            )
            return None
        self.plan.write(adapter, content)
        return './' + adapter.relative_to(self.plan.root).as_posix()

    def _allows_typed_imports(self) -> bool:
        config = self._load().typescript
        if isinstance(config, ManualSource):
            issue = MigrationIssue(self.plan.root / 'tsconfig.json', 1, config.message)
            if issue not in self.plan.issues:
                self.plan.issues.append(issue)
            return False
        return config.typedImports
