// This file was generated by lezer-generator and converted to TypeScript.
// To generate, run :
// `pnpm dlx @lezer/generator@^1.0.0 ./js/trace-viewer/preview/json.grammar -o ./js/trace-viewer/preview/extended-json-parser`
export const JsonText = 1,
    True = 2,
    False = 3,
    Null = 4,
    Number = 5,
    String = 6,
    Object = 9,
    Property = 10,
    PropertyName = 11,
    Array = 16;
