// Inline the plugin version at build time. Reading package.json at runtime would
// resolve relative to wherever the emitted module ends up, which silently reads the
// consuming application's package.json once anything bundles us.
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("../", import.meta.url);
const { version } = JSON.parse(readFileSync(new URL("package.json", root), "utf8"));
writeFileSync(
  new URL("src/version.ts", root),
  `// Generated by scripts/generate-version.mjs. Do not edit.\nexport const version = ${JSON.stringify(version)};\n`,
);
