name: Prace.js
on:
  pull_request:
    types:
      [
        "opened",
        "edited",
        "reopened",
        "synchronize",
        "review_requested",
        "review_request_removed",
        "assigned",
        "unassigned",
        "labeled",
        "unlabeled",
      ]

jobs:
  linting:
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'dependabot/')"
    steps:
      - uses: innerspacetrainings/Prace.js@114c0d1dc655d7ce3b7a1746bcd3c1c699f7a68c # v1.1.1 (master security fixes)
        with:
          configuration-path: .github/prace.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
