name: publish docs

on: workflow_dispatch

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Setup git config
        run: |
          git config --global --add safe.directory /__w/dara/dara
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          version: 2026.9.0
      - name: Get version
        id: get-version
        # Retrieves version from '"version": "<version>"' line in lerna.json
        run: |
          version=$(sed -n 's/.*"version": "\(.*\)".*/\1/p' lerna.json)
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Package and Publish Docs
        run: mise run publish-docs
        env:
          PROJECT: causalens-internal
          LOCATION: us-central1
          REPOSITORY: documentation
          PACKAGE: dara
          GAR_USERNAME: _json_key
          GAR_KEY_JSON: '${{ secrets.GAR_KEY_JSON }}'
          VERSION: ${{ steps.get-version.outputs.version }}