
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "decision_app"
version = "1.16.2"
description = "Decision App"
authors = ["Author <author@example.com>"]
source = []

[tool.poetry.dependencies]
python = ">=3.9.0, <3.13.0"
dara-core = "^1.15.7"
dara-components = "^1.15.7"

[tool.poetry.dev-dependencies]
blue = "^0.9.1"
isort = "^5.10.1"

[tool.poetry.dev-dependencies.dara-core]
develop = true
path = "../dara-core/"

[tool.poetry.dev-dependencies.dara-components]
develop = true
path = "../dara-components/"

[tool.blue]
line-length = 120

[tool.isort]
known_dara = ["dara"]
profile = "black"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DARA", "FIRSTPARTY", "LOCALFOLDER"]
